### ISSUE TITLE
street map disappears

### ISSUE THREAD

**Issue by leekinney** [whathood/whathood#30]
When you search for an address the specific neighborhood map pops up and then disappears after a few seconds bringing you back to the main philly map.

**Comment by leekinney** [comment]
Although the neighborhood isn't disappearing anymore, overlay is confusing and makes it really difficult to see the streets. 
![screen shot 2015-08-20 at 6 03 35 pm](https://cloud.githubusercontent.com/assets/4022077/9396942/4e221c8e-4766-11e5-9044-afe53412a6f5.png)

**Comment by jimRsmiley** [comment]
that's a different bug.
