### ISSUE TITLE
Build a Go / Submit button

### ISSUE THREAD

**Issue by KGalley** [whathood/whathood#31]
We think it would be helpful to add a go/ submit button on the landing page after you enter your address.  This esp would be helpful on mobile.

**Comment by jimRsmiley** [comment]
@KGalley, @leekinney do you want to give me the html for that?

**Comment by leekinney** [comment]
@jimRsmiley We're possibly going to meet up tonight or Monday to get the form working. Will send it over as soon as it's done!

**Comment by jimRsmiley** [comment]
this is done
