### ISSUE TITLE
No link to github source

### ISSUE THREAD

**Issue by bennovack** [whathood/whathood#48]
Potential contributors won't know there's open source they could contribute to without a link. Maybe in the top navbar?

**Comment by jimRsmiley** [comment]
@bennovack yup, sounds good. I'll make make that my next update.

**Comment by jimRsmiley** [comment]
Fixed with commit

https://github.com/whathood/whathood/commit/d5be0cf4144940b57012db2861a3b00d48591611

@bennovack I referenced my CFP project page, is that cool?

**Comment by bennovack** [comment]
@jimRsmiley It is very cool. Thanks!
